version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuserpass
      POSTGRES_DB: testdb
    ports:
     - 3306:3306
  hive:
    depends_on:
      - db
    image: steemit/hive
    build: .
    environment:
      DATABASE_URL: postgresql://testuser:testuserpass@db:5432/testdb
      LOG_LEVEL: INFO
      STEEMD_URL: 10.10.2.4:8080
    links:
      - db:db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    restart: always
